
package Beuzelin;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Color;

public class MainVue extends javax.swing.JFrame {
    
    private Controleur c;
    private VueSilo s;
    private Alarme a;
    
    public MainVue() {
        initComponents();
        c = new Controleur();
        a = new Alarme("Je suis l'alarme de test",false);
        majAlarme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reception = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        expedition = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        silo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        jPanel1.setLayout(new java.awt.BorderLayout());

        reception.setText("Reception");
        reception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionActionPerformed(evt);
            }
        });
        jPanel1.add(reception, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        expedition.setText("Expedition");
        expedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expeditionActionPerformed(evt);
            }
        });
        jPanel2.add(expedition, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        silo.setText("Silo");
        silo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siloActionPerformed(evt);
            }
        });
        jPanel4.add(silo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>                        

    private void receptionActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
        VueReception r = new VueReception(this,true);
        r.setVisible(true);
        this.setVisible(true);
    }                                        

    private void expeditionActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
        VueExpedition e = new VueExpedition(this, true);
        e.setVisible(true);
        this.setVisible(true);
    }                                        

    private void siloActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
        s = new VueSilo(this,true);
        initSilo();
        s.setVisible(true);
        this.setVisible(true);
        if(s.select!=-1){
            a.stopAlarme();
            jPanel3.setBackground(Color.green);
            majBD(s.select-1, s.action);
        }
        majAlarme();
    }
    
    private void initSilo(){
        s.mini1.setText("0");
        s.mini2.setText("0");
        s.mini3.setText("0");
        s.mini4.setText("0");
        s.mini5.setText("0");
        s.mini6.setText("0");
        s.mini7.setText("0");
        s.mini8.setText("0");
        s.mini9.setText("0");
        s.mini10.setText("0");
        
        s.max1.setText(""+c.getSilo().getCellule(0).getPoidsMax());
        s.max2.setText(""+c.getSilo().getCellule(1).getPoidsMax());
        s.max3.setText(""+c.getSilo().getCellule(2).getPoidsMax());
        s.max4.setText(""+c.getSilo().getCellule(3).getPoidsMax());
        s.max5.setText(""+c.getSilo().getCellule(4).getPoidsMax());
        s.max6.setText(""+c.getSilo().getCellule(5).getPoidsMax());
        s.max7.setText(""+c.getSilo().getCellule(6).getPoidsMax());
        s.max8.setText(""+c.getSilo().getCellule(7).getPoidsMax());
        s.max9.setText(""+c.getSilo().getCellule(8).getPoidsMax());
        s.max10.setText(""+c.getSilo().getCellule(9).getPoidsMax());
        
        s.temp1.setText(""+c.getSilo().getCellule(0).getSonde());
        s.temp2.setText(""+c.getSilo().getCellule(1).getSonde());
        s.temp3.setText(""+c.getSilo().getCellule(2).getSonde());
        s.temp4.setText(""+c.getSilo().getCellule(3).getSonde());
        s.temp5.setText(""+c.getSilo().getCellule(4).getSonde());
        s.temp6.setText(""+c.getSilo().getCellule(5).getSonde());
        s.temp7.setText(""+c.getSilo().getCellule(6).getSonde());
        s.temp8.setText(""+c.getSilo().getCellule(7).getSonde());
        s.temp9.setText(""+c.getSilo().getCellule(8).getSonde());
        s.temp10.setText(""+c.getSilo().getCellule(9).getSonde());
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        s.actu1.setText("N:"+formatter.format(c.getSilo().getCellule(0).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(0).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(0).getTraitement()));
        s.actu2.setText("N:"+formatter.format(c.getSilo().getCellule(1).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(1).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(1).getTraitement()));
        s.actu3.setText("N:"+formatter.format(c.getSilo().getCellule(2).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(2).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(2).getTraitement()));
        s.actu4.setText("N:"+formatter.format(c.getSilo().getCellule(3).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(3).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(3).getTraitement()));
        s.actu5.setText("N:"+formatter.format(c.getSilo().getCellule(4).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(4).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(4).getTraitement()));
        s.actu6.setText("N:"+formatter.format(c.getSilo().getCellule(5).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(5).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(5).getTraitement()));
        s.actu7.setText("N:"+formatter.format(c.getSilo().getCellule(6).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(6).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(6).getTraitement()));
        s.actu8.setText("N:"+formatter.format(c.getSilo().getCellule(7).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(7).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(7).getTraitement()));
        s.actu9.setText("N:"+formatter.format(c.getSilo().getCellule(8).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(8).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(8).getTraitement()));
        s.actu10.setText("N:"+formatter.format(c.getSilo().getCellule(9).getNettoyage())+"\nV:"+formatter.format(c.getSilo().getCellule(9).getVentilation())+"\nT:"+formatter.format(c.getSilo().getCellule(9).getTraitement()));
    
        s.carre1.setBounds(25,500,25,350);
/*        s.temp2.setText(""+c.getSilo().getCellule(1).getTempMoy());
        s.temp3.setText(""+c.getSilo().getCellule(2).getTempMoy());
        s.temp4.setText(""+c.getSilo().getCellule(3).getTempMoy());
        s.temp5.setText(""+c.getSilo().getCellule(4).getTempMoy());
        s.temp6.setText(""+c.getSilo().getCellule(5).getTempMoy());
        s.temp7.setText(""+c.getSilo().getCellule(6).getTempMoy());
        s.temp8.setText(""+c.getSilo().getCellule(7).getTempMoy());
        s.temp9.setText(""+c.getSilo().getCellule(8).getTempMoy());
        s.temp10.setText(""+c.getSilo().getCellule(9).getTempMoy());*/
    }
    
    private void majBD(int i, int j){
        Date auj = new Date();
        if(j==1)
            c.getSilo().getCellule(i).setNettoyage(auj);
        else if (j==2){
            c.getSilo().getCellule(i).setVentilation(auj);
            c.getSilo().getCellule(i).getSonde().setTemperature(c.getSilo().getCellule(i).getSonde().getTemperature()-5);
        }
        else if (j==3)
            c.getSilo().getCellule(i).setTraitement(auj);
        else
            jPanel3.setBackground(Color.yellow);
    }
    
    private void majAlarme(){
        for (int i=0;i<c.getSilo().getNbCellule();i++){
            if (c.getSilo().getCellule(i).getSonde().getTemperature()>23){
                a.setActive(true);
                jPanel3.setBackground(Color.red);
            }
        }
        if (!a.isActive()){
            jPanel3.setBackground(Color.green);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton reception;
    private javax.swing.JButton expedition;
    private javax.swing.JButton silo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration                   
}
