/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beuzelin;


import java.lang.Math;

public class VueInfo extends javax.swing.JDialog {

    public InfoCereales info;
    
    public VueInfo(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infocategorie = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        infoqualite = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infopoids = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoaffichage = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infovolume = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        infoannuler = new javax.swing.JButton();
        vide = new javax.swing.JPanel();
        infovalider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        jPanel1.setLayout(new java.awt.BorderLayout());

        infocategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "blé", "colza", "pois", "proteagineux", "orge" }));
        jPanel1.add(infocategorie, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        infoqualite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "très bon", "bon", "mauvais" }));
        jPanel3.add(infoqualite, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        infopoids.setColumns(20);
        infopoids.setRows(5);
        jScrollPane2.setViewportView(infopoids);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Poids :");
        jPanel4.add(jLabel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        infoaffichage.setColumns(20);
        infoaffichage.setRows(5);
        jScrollPane1.setViewportView(infoaffichage);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        infovolume.setColumns(20);
        infovolume.setRows(5);
        jScrollPane3.setViewportView(infovolume);

        jPanel6.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Volume :");
        jPanel6.add(jLabel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel6);

        infoannuler.setText("Annuler");
        infoannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoannulerActionPerformed(evt);
            }
        });
        getContentPane().add(infoannuler);

        javax.swing.GroupLayout videLayout = new javax.swing.GroupLayout(vide);
        vide.setLayout(videLayout);
        videLayout.setHorizontalGroup(
            videLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        videLayout.setVerticalGroup(
            videLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(vide);

        infovalider.setText("Valider");
        infovalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infovaliderActionPerformed(evt);
            }
        });
        getContentPane().add(infovalider);

        pack();
    }// </editor-fold>                        

    private void infoannulerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.dispose();
    }                                           

    private void infovaliderActionPerformed(java.awt.event.ActionEvent evt) {
        if (infopoids.getText().equals(""))
            infoaffichage.setText("Pas de poids");
        else if (infovolume.getText().equals(""))
            infoaffichage.setText("Pas de volume");
        else {
            infoaffichage.setText(infocategorie.getSelectedItem().toString());
            String categorie=infocategorie.getSelectedItem().toString();
            int poids=Integer.parseInt(infopoids.getText());
            String qualite=infoqualite.getSelectedItem().toString();
            int numLot=((int)(1 + (Math.random() * (1000 - 1) )));
            int volume=Integer.parseInt(infovolume.getText());
            info = new InfoCereales(categorie,poids,qualite,numLot,volume);
            this.dispose();
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueInfo dialog = new VueInfo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea infoaffichage;
    private javax.swing.JButton infoannuler;
    private javax.swing.JComboBox<String> infocategorie;
    private javax.swing.JTextArea infopoids;
    private javax.swing.JComboBox<String> infoqualite;
    private javax.swing.JButton infovalider;
    private javax.swing.JTextArea infovolume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel vide;
    // End of variables declaration                   
}
