package Beuzelin;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author af077964
 */
public class VueSilo extends javax.swing.JDialog {
    
    public int select;
    public int action;
    
    public VueSilo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panneau = new javax.swing.JPanel();
        cell1 = new javax.swing.JPanel();
        affichage1 = new javax.swing.JPanel();
        carre1 = new javax.swing.JPanel();
        stats1 = new javax.swing.JPanel();
        max1 = new javax.swing.JLabel();
        temp1 = new javax.swing.JLabel();
        selection1 = new javax.swing.JRadioButton();
        actu1 = new javax.swing.JTextArea();
        mini1 = new javax.swing.JLabel();
        cell2 = new javax.swing.JPanel();
        affichage2 = new javax.swing.JPanel();
        carre2 = new javax.swing.JPanel();
        stats2 = new javax.swing.JPanel();
        max2 = new javax.swing.JLabel();
        temp2 = new javax.swing.JLabel();
        selection2 = new javax.swing.JRadioButton();
        actu2 = new javax.swing.JTextArea();
        mini2 = new javax.swing.JLabel();
        cell3 = new javax.swing.JPanel();
        affichage3 = new javax.swing.JPanel();
        carre3 = new javax.swing.JPanel();
        stats3 = new javax.swing.JPanel();
        max3 = new javax.swing.JLabel();
        temp3 = new javax.swing.JLabel();
        selection3 = new javax.swing.JRadioButton();
        actu3 = new javax.swing.JTextArea();
        mini3 = new javax.swing.JLabel();
        cell4 = new javax.swing.JPanel();
        affichage4 = new javax.swing.JPanel();
        carre4 = new javax.swing.JPanel();
        stats4 = new javax.swing.JPanel();
        max4 = new javax.swing.JLabel();
        temp4 = new javax.swing.JLabel();
        selection4 = new javax.swing.JRadioButton();
        actu4 = new javax.swing.JTextArea();
        mini4 = new javax.swing.JLabel();
        cell5 = new javax.swing.JPanel();
        affichage5 = new javax.swing.JPanel();
        carre5 = new javax.swing.JPanel();
        stats5 = new javax.swing.JPanel();
        max5 = new javax.swing.JLabel();
        temp5 = new javax.swing.JLabel();
        selection5 = new javax.swing.JRadioButton();
        actu5 = new javax.swing.JTextArea();
        mini5 = new javax.swing.JLabel();
        cell6 = new javax.swing.JPanel();
        affichage6 = new javax.swing.JPanel();
        carre6 = new javax.swing.JPanel();
        stats6 = new javax.swing.JPanel();
        max6 = new javax.swing.JLabel();
        temp6 = new javax.swing.JLabel();
        selection6 = new javax.swing.JRadioButton();
        actu6 = new javax.swing.JTextArea();
        mini6 = new javax.swing.JLabel();
        cell7 = new javax.swing.JPanel();
        affichage7 = new javax.swing.JPanel();
        carre7 = new javax.swing.JPanel();
        stats7 = new javax.swing.JPanel();
        max7 = new javax.swing.JLabel();
        temp7 = new javax.swing.JLabel();
        selection7 = new javax.swing.JRadioButton();
        actu7 = new javax.swing.JTextArea();
        mini7 = new javax.swing.JLabel();
        cell8 = new javax.swing.JPanel();
        affichage8 = new javax.swing.JPanel();
        carre8 = new javax.swing.JPanel();
        stats8 = new javax.swing.JPanel();
        max8 = new javax.swing.JLabel();
        temp8 = new javax.swing.JLabel();
        selection8 = new javax.swing.JRadioButton();
        actu8 = new javax.swing.JTextArea();
        mini8 = new javax.swing.JLabel();
        cell9 = new javax.swing.JPanel();
        affichage9 = new javax.swing.JPanel();
        carre9 = new javax.swing.JPanel();
        stats9 = new javax.swing.JPanel();
        max9 = new javax.swing.JLabel();
        temp9 = new javax.swing.JLabel();
        selection9 = new javax.swing.JRadioButton();
        actu9 = new javax.swing.JTextArea();
        mini9 = new javax.swing.JLabel();
        cell10 = new javax.swing.JPanel();
        affichage10 = new javax.swing.JPanel();
        carre10 = new javax.swing.JPanel();
        stats10 = new javax.swing.JPanel();
        max10 = new javax.swing.JLabel();
        temp10 = new javax.swing.JLabel();
        selection10 = new javax.swing.JRadioButton();
        actu10 = new javax.swing.JTextArea();
        mini10 = new javax.swing.JLabel();
        Bouton = new javax.swing.JPanel();
        silonettoyage = new javax.swing.JButton();
        siloventilation = new javax.swing.JButton();
        silotraitement = new javax.swing.JButton();
        siloannuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        Panneau.setLayout(new java.awt.GridLayout(2, 5));

        cell1.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage1Layout = new javax.swing.GroupLayout(affichage1);
        affichage1.setLayout(affichage1Layout);
        affichage1Layout.setHorizontalGroup(
            affichage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage1Layout.setVerticalGroup(
            affichage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        carre1.setBounds(25,25,25,75); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre1.setBackground(Color.black);
        
        affichage1.add(carre1);
                
        cell1.add(affichage1);

        stats1.setLayout(new java.awt.GridLayout(5, 1));

        max1.setText("max1 genre bcp");
        stats1.add(max1);

        temp1.setText("il fait cho");
        stats1.add(temp1);

        buttonGroup1.add(selection1);
        selection1.setText("Cellule 1");
        stats1.add(selection1);

        actu1.setText("pas trop");
        stats1.add(actu1);

        mini1.setText("pas beaucoup");
        stats1.add(mini1);

        cell1.add(stats1);

        Panneau.add(cell1);

        cell2.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage2Layout = new javax.swing.GroupLayout(affichage2);
        affichage2.setLayout(affichage2Layout);
        affichage2Layout.setHorizontalGroup(
            affichage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage2Layout.setVerticalGroup(
            affichage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre2.setBounds(25,25,25,65); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre2.setBackground(Color.black);
        
        affichage2.add(carre2);

        cell2.add(affichage2);

        stats2.setLayout(new java.awt.GridLayout(5, 1));

        max2.setText("jLabel1");
        stats2.add(max2);

        temp2.setText("jLabel2");
        stats2.add(temp2);

        buttonGroup1.add(selection2);
        selection2.setText("Cellule 2");
        stats2.add(selection2);

        actu2.setText("jLabel3");
        stats2.add(actu2);

        mini2.setText("jLabel4");
        stats2.add(mini2);

        cell2.add(stats2);

        Panneau.add(cell2);

        cell3.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage3Layout = new javax.swing.GroupLayout(affichage3);
        affichage3.setLayout(affichage3Layout);
        affichage3Layout.setHorizontalGroup(
            affichage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage3Layout.setVerticalGroup(
            affichage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre3.setBounds(25,25,25,25); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre3.setBackground(Color.black);
        
        affichage3.add(carre3);
        
        cell3.add(affichage3);

        stats3.setLayout(new java.awt.GridLayout(5, 1));

        max3.setText("jLabel1");
        stats3.add(max3);

        temp3.setText("jLabel2");
        stats3.add(temp3);

        buttonGroup1.add(selection3);
        selection3.setText("Cellule 3");
        stats3.add(selection3);

        actu3.setText("jLabel3");
        stats3.add(actu3);

        mini3.setText("jLabel4");
        stats3.add(mini3);

        cell3.add(stats3);

        Panneau.add(cell3);

        cell4.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage4Layout = new javax.swing.GroupLayout(affichage4);
        affichage4.setLayout(affichage4Layout);
        affichage4Layout.setHorizontalGroup(
            affichage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage4Layout.setVerticalGroup(
            affichage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre4.setBounds(25,25,25,85); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre4.setBackground(Color.black);
        
        affichage4.add(carre4);

        cell4.add(affichage4);

        stats4.setLayout(new java.awt.GridLayout(5, 1));

        max4.setText("jLabel1");
        stats4.add(max4);

        temp4.setText("jLabel2");
        stats4.add(temp4);

        buttonGroup1.add(selection4);
        selection4.setText("Cellule 4");
        stats4.add(selection4);

        actu4.setText("jLabel3");
        stats4.add(actu4);

        mini4.setText("jLabel4");
        stats4.add(mini4);

        cell4.add(stats4);

        Panneau.add(cell4);

        cell5.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage5Layout = new javax.swing.GroupLayout(affichage5);
        affichage5.setLayout(affichage5Layout);
        affichage5Layout.setHorizontalGroup(
            affichage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage5Layout.setVerticalGroup(
            affichage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre5.setBounds(25,25,25,35); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre5.setBackground(Color.black);
        
        affichage5.add(carre5);

        cell5.add(affichage5);

        stats5.setLayout(new java.awt.GridLayout(5, 1));

        max5.setText("jLabel1");
        stats5.add(max5);

        temp5.setText("jLabel2");
        stats5.add(temp5);

        buttonGroup1.add(selection5);
        selection5.setText("Cellule 5");
        stats5.add(selection5);

        actu5.setText("jLabel3");
        stats5.add(actu5);

        mini5.setText("jLabel4");
        stats5.add(mini5);

        cell5.add(stats5);

        Panneau.add(cell5);

        cell6.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage6Layout = new javax.swing.GroupLayout(affichage6);
        affichage6.setLayout(affichage6Layout);
        affichage6Layout.setHorizontalGroup(
            affichage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage6Layout.setVerticalGroup(
            affichage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre6.setBounds(25,25,25,5); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre6.setBackground(Color.black);
        
        affichage6.add(carre6);

        cell6.add(affichage6);

        stats6.setLayout(new java.awt.GridLayout(5, 1));

        max6.setText("comme le 1 mais pour le 6");
        stats6.add(max6);

        temp6.setText("OH");
        stats6.add(temp6);

        buttonGroup1.add(selection6);
        selection6.setText("Cellule 2");
        stats6.add(selection6);

        actu6.setText("oui");
        stats6.add(actu6);

        mini6.setText("pas trop");
        stats6.add(mini6);

        cell6.add(stats6);

        Panneau.add(cell6);

        cell7.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage7Layout = new javax.swing.GroupLayout(affichage7);
        affichage7.setLayout(affichage7Layout);
        affichage7Layout.setHorizontalGroup(
            affichage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage7Layout.setVerticalGroup(
            affichage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre7.setBounds(25,25,25,45); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre7.setBackground(Color.black);
        
        affichage7.add(carre7);

        cell7.add(affichage7);

        stats7.setLayout(new java.awt.GridLayout(5, 1));

        max7.setText("jLabel1");
        stats7.add(max7);

        temp7.setText("jLabel2");
        stats7.add(temp7);

        buttonGroup1.add(selection7);
        selection7.setText("Cellule 7");
        stats7.add(selection7);

        actu7.setText("jLabel3");
        stats7.add(actu7);

        mini7.setText("jLabel4");
        stats7.add(mini7);

        cell7.add(stats7);

        Panneau.add(cell7);

        cell8.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage8Layout = new javax.swing.GroupLayout(affichage8);
        affichage8.setLayout(affichage8Layout);
        affichage8Layout.setHorizontalGroup(
            affichage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage8Layout.setVerticalGroup(
            affichage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre8.setBounds(25,25,25,55); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre8.setBackground(Color.black);
        
        affichage8.add(carre8);

        cell8.add(affichage8);

        stats8.setLayout(new java.awt.GridLayout(5, 1));

        max8.setText("jLabel1");
        stats8.add(max8);

        temp8.setText("jLabel2");
        stats8.add(temp8);

        buttonGroup1.add(selection8);
        selection8.setText("Cellule 8");
        stats8.add(selection8);

        actu8.setText("jLabel3");
        stats8.add(actu8);

        mini8.setText("jLabel4");
        stats8.add(mini8);

        cell8.add(stats8);

        Panneau.add(cell8);

        cell9.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage9Layout = new javax.swing.GroupLayout(affichage9);
        affichage9.setLayout(affichage9Layout);
        affichage9Layout.setHorizontalGroup(
            affichage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage9Layout.setVerticalGroup(
            affichage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre9.setBounds(25,25,25,25); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre9.setBackground(Color.black);
        
        affichage9.add(carre9);

        cell9.add(affichage9);

        stats9.setLayout(new java.awt.GridLayout(5, 1));

        max9.setText("jLabel1");
        stats9.add(max9);

        temp9.setText("jLabel2");
        stats9.add(temp9);

        buttonGroup1.add(selection9);
        selection9.setText("Cellule 9");
        stats9.add(selection9);

        actu9.setText("jLabel3");
        stats9.add(actu9);

        mini9.setText("jLabel4");
        stats9.add(mini9);

        cell9.add(stats9);

        Panneau.add(cell9);

        cell10.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout affichage10Layout = new javax.swing.GroupLayout(affichage10);
        affichage10.setLayout(affichage10Layout);
        affichage10Layout.setHorizontalGroup(
            affichage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        affichage10Layout.setVerticalGroup(
            affichage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        
        carre10.setBounds(25,25,25,125); /////////////////////////////////////////////////////////setup here pour la taille du carré rigolo (x,y,largeur,hauteur)
        carre10.setBackground(Color.black);
        
        affichage10.add(carre10);

        cell10.add(affichage10);

        stats10.setLayout(new java.awt.GridLayout(5, 1));

        max10.setText("jLabel1");
        stats10.add(max10);

        temp10.setText("jLabel2");
        stats10.add(temp10);

        buttonGroup1.add(selection10);
        selection10.setText("Cellule 10");
        stats10.add(selection10);

        actu10.setText("jLabel3");
        stats10.add(actu10);

        mini10.setText("jLabel4");
        stats10.add(mini10);

        cell10.add(stats10);

        Panneau.add(cell10);

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        Bouton.setLayout(new java.awt.GridLayout(4, 1));

        silonettoyage.setText("Nettoyage");
        Bouton.add(silonettoyage);
        silonettoyage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silonettoyageActionPerformed(evt);
            }
        });

        siloventilation.setText("Ventilation");
        Bouton.add(siloventilation);
        siloventilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siloventilationActionPerformed(evt);
            }
        });

        silotraitement.setText("Traitement");
        Bouton.add(silotraitement);
        silotraitement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silotraitemenntActionPerformed(evt);
            }
        });
        
        siloannuler.setText("Annuler");
        Bouton.add(siloannuler);
        siloannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siloannulerActionPerformed(evt);
            }
        });

        getContentPane().add(Bouton, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>                        
   
    
    private void siloannulerActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.dispose();
    }  
    
    private void silonettoyageActionPerformed(java.awt.event.ActionEvent evt) {
        select=this.getSelection();
        action=1;
        this.dispose();
    } 
    
    private void siloventilationActionPerformed(java.awt.event.ActionEvent evt) {
        select=this.getSelection();
        action=2;
        this.dispose();
    } 
    
    private void silotraitemenntActionPerformed(java.awt.event.ActionEvent evt) {
        select=this.getSelection();
        action=3;
        this.dispose();
    } 
    
    
    
    private int getSelection(){
        int temp;
        if (selection1.isSelected())
            return temp=1;
        else if (selection2.isSelected())
            return temp=2;
        else if (selection3.isSelected())
            return temp=3;
        else if (selection4.isSelected())
            return temp=4;
        else if (selection5.isSelected())
            return temp=5;
        else if (selection6.isSelected())
            return temp=6;
        else if (selection7.isSelected())
            return temp=7;
        else if (selection8.isSelected())
            return temp=8;
        else if (selection9.isSelected())
            return temp=9;
        else if (selection10.isSelected())
            return temp=10;
        else return temp=-1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueSilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueSilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueSilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueSilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueSilo dialog = new VueSilo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Bouton;
    private javax.swing.JPanel Panneau;
    public javax.swing.JTextArea actu1;
    public javax.swing.JTextArea actu10;
    public javax.swing.JTextArea actu2;
    public javax.swing.JTextArea actu3;
    public javax.swing.JTextArea actu4;
    public javax.swing.JTextArea actu5;
    public javax.swing.JTextArea actu6;
    public javax.swing.JTextArea actu7;
    public javax.swing.JTextArea actu8;
    public javax.swing.JTextArea actu9;
    public javax.swing.JPanel carre1;
    public javax.swing.JPanel carre2;
    public javax.swing.JPanel carre3;
    public javax.swing.JPanel carre4;
    public javax.swing.JPanel carre5;
    public javax.swing.JPanel carre6;
    public javax.swing.JPanel carre7;
    public javax.swing.JPanel carre8;
    public javax.swing.JPanel carre9;
    public javax.swing.JPanel carre10;  
    private javax.swing.JPanel affichage1;
    private javax.swing.JPanel affichage10;
    private javax.swing.JPanel affichage2;
    private javax.swing.JPanel affichage3;
    private javax.swing.JPanel affichage4;
    private javax.swing.JPanel affichage5;
    private javax.swing.JPanel affichage6;
    private javax.swing.JPanel affichage7;
    private javax.swing.JPanel affichage8;
    private javax.swing.JPanel affichage9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cell1;
    private javax.swing.JPanel cell10;
    private javax.swing.JPanel cell2;
    private javax.swing.JPanel cell3;
    private javax.swing.JPanel cell4;
    private javax.swing.JPanel cell5;
    private javax.swing.JPanel cell6;
    private javax.swing.JPanel cell7;
    private javax.swing.JPanel cell8;
    private javax.swing.JPanel cell9;
    private javax.swing.JButton silonettoyage;
    private javax.swing.JButton siloventilation;
    private javax.swing.JButton silotraitement;
    private javax.swing.JButton siloannuler;
    public javax.swing.JLabel max1;
    public javax.swing.JLabel max10;
    public javax.swing.JLabel max2;
    public javax.swing.JLabel max3;
    public javax.swing.JLabel max4;
    public javax.swing.JLabel max5;
    public javax.swing.JLabel max6;
    public javax.swing.JLabel max7;
    public javax.swing.JLabel max8;
    public javax.swing.JLabel max9;
    public javax.swing.JLabel mini1;
    public javax.swing.JLabel mini10;
    public javax.swing.JLabel mini2;
    public javax.swing.JLabel mini3;
    public javax.swing.JLabel mini4;
    public javax.swing.JLabel mini5;
    public javax.swing.JLabel mini6;
    public javax.swing.JLabel mini7;
    public javax.swing.JLabel mini8;
    public javax.swing.JLabel mini9;
    private javax.swing.JRadioButton selection1;
    private javax.swing.JRadioButton selection10;
    private javax.swing.JRadioButton selection2;
    private javax.swing.JRadioButton selection3;
    private javax.swing.JRadioButton selection4;
    private javax.swing.JRadioButton selection5;
    private javax.swing.JRadioButton selection6;
    private javax.swing.JRadioButton selection7;
    private javax.swing.JRadioButton selection8;
    private javax.swing.JRadioButton selection9;
    public javax.swing.JPanel stats1;
    public javax.swing.JPanel stats10;
    public javax.swing.JPanel stats2;
    public javax.swing.JPanel stats3;
    public javax.swing.JPanel stats4;
    public javax.swing.JPanel stats5;
    public javax.swing.JPanel stats6;
    public javax.swing.JPanel stats7;
    public javax.swing.JPanel stats8;
    public javax.swing.JPanel stats9;
    public javax.swing.JLabel temp1;
    public javax.swing.JLabel temp10;
    public javax.swing.JLabel temp2;
    public javax.swing.JLabel temp3;
    public javax.swing.JLabel temp4;
    public javax.swing.JLabel temp5;
    public javax.swing.JLabel temp6;
    public javax.swing.JLabel temp7;
    public javax.swing.JLabel temp8;
    public javax.swing.JLabel temp9;
    // End of variables declaration                   
}
