/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application.Vue;

/**
 *
 * @author af077964
 */
public class VueReception extends javax.swing.JDialog {

    public VueReception(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listeTransport = new javax.swing.JComboBox<>();
        infotext = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        affichagelistetransport = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        listeCellule = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        affichagelistecellule = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        info = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        affichageinfocéréale = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        receptionannuler = new javax.swing.JButton();
        receptionvalider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jPanel1.setLayout(new java.awt.BorderLayout());

        listeTransport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(listeTransport, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        infotext.setLayout(new java.awt.BorderLayout());

        affichagelistetransport.setColumns(20);
        affichagelistetransport.setRows(5);
        jScrollPane1.setViewportView(affichagelistetransport);

        infotext.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(infotext);

        jPanel2.setLayout(new java.awt.BorderLayout());

        listeCellule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(listeCellule, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        affichagelistecellule.setViewportView(jTextArea1);

        jPanel3.add(affichagelistecellule, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        info.setText("Infos du lot de céréale");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        affichageinfocéréale.setViewportView(jTextArea2);

        jPanel4.add(affichageinfocéréale, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4);

        receptionannuler.setText("Annuler");
        receptionannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionannulerActionPerformed(evt);
            }
        });
        getContentPane().add(receptionannuler);

        receptionvalider.setText("Valider");
        receptionvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionvaliderActionPerformed(evt);
            }
        });
        getContentPane().add(receptionvalider);

        pack();
    }// </editor-fold>                        

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setVisible(false);
        VueInfo i = new VueInfo(this,true);
        i.setVisible(true);
        this.setVisible(true);
    }  
    
    private void receptionannulerActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.dispose();
    }                                                

    private void receptionvaliderActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                                                  

    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueReception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueReception dialog = new VueReception(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane affichageinfocéréale;
    private javax.swing.JScrollPane affichagelistecellule;
    private javax.swing.JTextArea affichagelistetransport;
    private javax.swing.JButton info;
    private javax.swing.JPanel infotext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> listeCellule;
    private javax.swing.JComboBox<String> listeTransport;
    private javax.swing.JButton receptionannuler;
    private javax.swing.JButton receptionvalider;
    // End of variables declaration                   
}
